name: Deploy API to Gravitee

on:
  push:
    paths:
      - "gravitee/007.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy V2 API to Gravitee
        run: |
          echo "Sending API definition to Gravitee..."
          response=$(curl --request POST \
            --url "$GRAVITEE_API_URL/management/organizations/$ORG_ID/environments/$ENV_ID/apis/import" \
            --header "Authorization: Bearer $GRAVITEE_TOKEN" \
            --header "Content-Type: application/json" \
            --data @gravitee/007.json \
            --silent --write-out "HTTPSTATUS:%{http_code}")

          # Extract body and status
          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

          echo "HTTP Status Code: $status"
          echo "Response Body:"
          echo "$body"

          if [ "$status" -ge 400 ]; then
            echo "Import failed with status $status"
            exit 1
          else
            echo "Import succeeded"
          fi
        env:
          GRAVITEE_API_URL: ${{ secrets.GRAVITEE_API_URL }}
          GRAVITEE_TOKEN: ${{ secrets.GRAVITEE_TOKEN }}
          ORG_ID: ${{ secrets.GRAVITEE_ORG_ID }}
          ENV_ID: ${{ secrets.GRAVITEE_ENV_ID }}
