name: Deploy API to Gravitee

on:
  push:
    paths:
      - "gravitee/api-definition.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy v2 API to Gravitee
        run: |
          curl --request POST \
            --url "$GRAVITEE_API_URL/management/organizations/$ORG_ID/environments/$ENV_ID/apis/import" \
            --header "Authorization: Bearer $GRAVITEE_TOKEN" \
            --header "Content-Type: application/json" \
            --data @gravitee/api-definition.json
        env:
          GRAVITEE_API_URL: ${{ secrets.GRAVITEE_API_URL }}
          GRAVITEE_TOKEN: ${{ secrets.GRAVITEE_TOKEN }}
          ORG_ID: ${{ secrets.ORG_ID }}
          ENV_ID: ${{ secrets.ENV_ID }}
