name: Deploy V4 API to Gravitee

on:
  push:
    paths:
      - "gravitee/v4/*.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy V4 API to Gravitee
        run: |
          echo "Sending V4 API definition to Gravitee..."
          response=$(curl --request POST \
            --url "$GRAVITEE_API_URL/management/v2/environments/$ENV_ID/apis/_import/definition" \
            --header "Authorization: Bearer $GRAVITEE_TOKEN" \
            --header "Content-Type: application/json" \
            --data @gravitee/v4/your-v4-api.json \
            --silent --write-out "HTTPSTATUS:%{http_code}")

          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

          echo "HTTP Status Code: $status"
          echo "Response Body:"
          echo "$body"

          if [ "$status" -ge 400 ]; then
            echo "Import failed with status $status"
            exit 1
          else
            echo "Import succeeded"
          fi
        env:
          GRAVITEE_API_URL: ${{ secrets.GRAVITEE_API_URL }}
          GRAVITEE_TOKEN: ${{ secrets.GRAVITEE_TOKEN }}
          ENV_ID: ${{ secrets.GRAVITEE_ENV_ID }}
