name: Promote Gravitee API

on:
  workflow_dispatch:
    inputs:
      api_id:
        description: "API ID to promote"
        required: true
      source_env_id:
        description: "Source Environment ID"
        default: "DEFAULT"
      target_env_id:
        description: "Target Environment ID (also Cockpit ID)"
        default: "e6993ff7-02d0-4c14-993f-f702d04c14f9"

env:
  GRAVITEE_API_URL: "https://demo-apim-api.geoff.gravitee.xyz"
  ORG_ID: "DEFAULT"

jobs:
  promote-api:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          echo "Validating inputs..."
          echo "API ID: ${{ github.event.inputs.api_id }}"
          echo "Source Env: ${{ github.event.inputs.source_env_id }}"
          echo "Target Env: ${{ github.event.inputs.target_env_id }}"
          
          if [[ ! "${{ github.event.inputs.api_id }}" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
            echo "❌ Invalid API ID format"
            exit 1
          fi

      - name: Promote API
        run: |
          echo "🚀 Starting API promotion"

          # Create temp file for payload to avoid heredoc indentation issues
          cat << EOF > payload.json
          {
            "targetEnvId": "${{ github.event.inputs.target_env_id }}",
            "targetEnvName": "Production",
            "targetEnvCockpitId": "${{ github.event.inputs.target_env_id }}",
            "withPolicies": true,
            "withPlans": true
          }
EOF
          
          echo "📦 Payload:"
          cat payload.json

          RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            -X POST \
            "$GRAVITEE_API_URL/management/organizations/$ORG_ID/environments/${{ github.event.inputs.source_env_id }}/apis/${{ github.event.inputs.api_id }}/_promote" \
            -H "Authorization: Bearer ${{ secrets.GRAVITEE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data @payload.json)

          HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g')

          echo "Status: $HTTP_STATUS"
          echo "Response:"
          echo "$BODY" | jq || echo "$BODY"

          if [ "$HTTP_STATUS" -ge 400 ]; then
            echo "❌ Promotion failed"
            exit 1
          else
            echo "✅ Successfully promoted API"
          fi
